### ISSUE TITLE
Block Store Microservice

### ISSUE THREAD

**Issue by mvandeberg** [koinos/koinos-block-store#1]
As a blockchain developer, I want a stand alone microservice to store immutable block information.

Note: Written in Go

- [x] Determine which key/value store is standard for Go and implement it (#2)
- [ ] Integrate RabbitMQ in to the `koinos-block-store` (#27)
- [x] Determine how do we handle API requests (#4)
- [x] Store/lookup block by id (map block id to block data) (#5)
- [x] Get ancestral blocks with height N (#6)
- [x] Store/lookup transaction by id (#7)
- [x] Store/lookup log by transaction id (#8)
- [x] CI Integration for Block Store Microservice (#11)
- [x] Integrate koinos-jsonrpc2-golang with blockstore (#25 )
